### ISSUE TITLE
Import 48D48 field map

### ISSUE THREAD

**Issue by seamusriordan** [JeffersonLab/g4sbs#2]
Field map file can be found here:

http://hallaweb.jlab.org/12GeV/SuperBigBite/downloads/GEN_10-map.txt

The axis Z is along the central ray to SBS (its front face is at z = 61 cm).
Target is located at x=0, y=0, z=341. 
The beam line at 17.5 degrees
The BigBite at 51.5 degrees at 155 cm from target.
The corner of the table x=-250, y=-250, z=-200, steps are 2 cm.
Number of steps = 251, 251, and 301

**Comment by leadmocha** [comment]
I think this is already implemented in the uconn_dev branch.

**Comment by seamusriordan** [comment]
Excellent.  Making this eventually in master and also storing the 48D48 maps on a Hall A server with the BigBite map (the path is in the readme) should finalize this.
